### ISSUE TITLE
nbclassic >=0.5 breaks jupyter_nbextensions_configurator

### ISSUE THREAD

**Issue by scmmmh** [Jupyter-contrib/jupyter_nbextensions_configurator#151]
Hi,

It seems that the nbclassic >= 0.5 releases break the jupyter_nbextensions_configurator extension, because it cannot find the corrected "marked.js" file. It is trying to load "/static/nbclassic/components/marked/lib/marked.js?v=20230228105802", but cannot find that. If I pin nbclassic < 0.5, then it works.

Migrated from https://github.com/jupyter/nbclassic/issues/227.

Best,
Mark

**Comment by ego** [comment]
I have the same problem
<img width="1265" alt="Screenshot 2023-02-28 at 17 05 23" src="https://user-images.githubusercontent.com/26470129/221925463-67cb4800-0fa0-4904-b9dd-7aec7f6b0659.png">

**Comment by mforbes** [comment]
This is quite problematic for new users.  Could `nbclassic<0.5` please be pinned until support for the upgraded marked is provided?

**Comment by echarles** [comment]
> This is quite problematic for new users. Could a quick release to PyPI pinning nbclassic<0.5 please be made until support for the upgraded marked is provided? (Looks like this is almost done? https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/152).

@juhasch What are your thoughts on this. Should we have a PR that pins to nbclassic<0.5, make a release, and then only after merge https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/152 and make the release?

**Comment by echarles** [comment]
nbclassic 0.5.4 is released and should fix this issue. Can anyone confirm and close this?

**Comment by paulhybryant** [comment]
No, I have nbclass 0.5.4 installed, and I am still getting this error.

```
main.js?v=20230407171327:1001 
        
       [jupyter_nbextensions_configurator] error loading zenmode/main:
TypeError: marked is not a function
build_extension_ui @ main.js?v=20230407171327:1001
render.js?v=20230407171327:155 
        
       Uncaught TypeError: marked is not a function
    at Object.render_markdown (render.js?v=20230407171327:155:13)
    at Object.success (main.js?v=20230407171327:582:26)
    at c (jquery.min.js:2:1)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:1)
    at l (jquery.min.js:2:1)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:1)
```

**Comment by echarles** [comment]
Thx for reporting @paulhybryant. I have tested in a blank env and the configurator works fine for `some` of the extensions, but indeed fails for the zenmode - see screenshots below. I would say this is due to an upgrade of zenmode, but is not managed by nbclassic, nor by the configurator extension. The best would be that you open an issue on the zenmode repo.

<img width="1405" alt="Screenshot 2023-04-07 at 11 53 09" src="https://user-images.githubusercontent.com/226720/230588682-7cd65be9-7ebd-4134-89de-9acaa1d14b4a.png">

<img width="1400" alt="Screenshot 2023-04-07 at 11 52 54" src="https://user-images.githubusercontent.com/226720/230588702-829b90c1-57b5-4277-82b7-dffe7d901f59.png">

<img width="307" alt="Screenshot 2023-04-07 at 11 52 57" src="https://user-images.githubusercontent.com/226720/230588709-5c183904-dc16-4f59-9112-c395ec5aa95f.png">

<img width="1400" alt="Screenshot 2023-04-07 at 11 53 30" src="https://user-images.githubusercontent.com/226720/230588721-85d727c4-8f54-4617-acce-6da52ff44918.png">

**Comment by xiphl** [comment]
Hi,
I am seeing the same error message as @paulhybryant in the configurator menu (with nbclassic 0.5.4) when i load the page using browser dev tools.
Although the extensions are working (ie I selected ExecuteTime and observed that the notebook did show the execute timing), the README part for each extensions are not showing up (see screenshot), does anyone have any suggestions on how to solve it?
![image](https://user-images.githubusercontent.com/50935738/230874144-a1a957f2-29a3-4349-8220-f8819c1a2c17.png)

**Comment by paulhybryant** [comment]
Yes, it is not just for zenmode. I didn't event have zenmode enabled. All the markdown description of the plugins have a blank description.

**Comment by echarles** [comment]
https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/154 is merged.

Next step is to cut a new release. @juhasch could you help with that?

**Comment by echarles** [comment]
@juhasch We need your help for a new release.

**Comment by XL1031** [comment]
> No, I have nbclass 0.5.4 installed, and I am still getting this error.
> 
> ```
> main.js?v=20230407171327:1001 
>         
>        [jupyter_nbextensions_configurator] error loading zenmode/main:
> TypeError: marked is not a function
> build_extension_ui @ main.js?v=20230407171327:1001
> render.js?v=20230407171327:155 
>         
>        Uncaught TypeError: marked is not a function
>     at Object.render_markdown (render.js?v=20230407171327:155:13)
>     at Object.success (main.js?v=20230407171327:582:26)
>     at c (jquery.min.js:2:1)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2:1)
>     at l (jquery.min.js:2:1)
>     at XMLHttpRequest.<anonymous> (jquery.min.js:2:1)
> ```

I also met this problem,how to deal with it?

**Comment by paulhybryant** [comment]
Is there a new release? Thanks!

**Comment by echarles** [comment]
@paulhybryant Yes, you can `pip instlall jupyter-nbextensions-configurator==0.6.3`

https://pypi.org/project/jupyter-nbextensions-configurator/0.6.3
