### ISSUE TITLE
extensions configured twice?

### ISSUE THREAD

**Issue by flying-sheep** [Jupyter-contrib/jupyter_nbextensions_configurator#25]
Hi, in my logs I get:

```
nbextension 'highlight_selected_word/main' has duplicate listings in both
'$HOME/.local/share/jupyter/nbextensions/highlight_selected_word/configurator.yaml' and
'$HOME/.local/share/jupyter/nbextensions/highlight_selected_word/configurator.yaml'
```

for each extension. (i added linebreaks for clarity)

but i have no configuration that could add another copy of that path AFAIK.

```console
$ ag nbextensions ~/.jupyter
$HOME/.jupyter/jupyter_notebook_config.json
4:      "jupyter_nbextensions_configurator": true

$HOME/.jupyter/jupyter_notebook_config.py
224:# c.NotebookApp.extra_nbextensions_path = traitlets.Undefined

$HOME/.jupyter/jupyter_nbconvert_config.json
5:      "jupyter_contrib_nbextensions.nbconvert_support.CodeFoldingPreprocessor",
6:      "jupyter_contrib_nbextensions.nbconvert_support.PyMarkdownPreprocessor"
11:      "$HOME/.local/lib/python3.5/site-packages/jupyter_contrib_nbextensions/templates"
15:    "postprocessor_class": "jupyter_contrib_nbextensions.nbconvert_support.EmbedPostProcessor"

$HOME/.jupyter/nbconfig/tree.json
3:    "nbextensions_configurator/tree_tab/main": true

$HOME/.jupyter/nbconfig/notebook.json
6:    "nbextensions_configurator/config_menu/main": true,
```

**Comment by jcb91** [comment]
Hmm, strange, particularly since they are both the same path. Seems that somehow the jupyter path contains duplicate entries, something which presumably happens from a jupyter config file somewhere else in the path. I'd suggest trying

    jupyter --paths

to find the full list of config directories on your system, then look in each of those for .py or .json config files

**Comment by jcb91** [comment]
did you make any progress on this, @flying-sheep?

**Comment by paulperry** [comment]
I have this problem, but I really do have duplicate paths:
`nbextension 'autosavetime/main' has duplicate listings in both '/Users/paulperry/anaconda3/share/jupyter/nbextensions/autosavetime/autosavetime.yaml' and '/Users/paulperry/Library/Jupyter/nbextensions/autosavetime/autosavetime.yaml'
`
my paths look like:
(root) ~>jupyter --paths
```
config:
    /Users/paulperry/.jupyter
    /Users/paulperry/anaconda3/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/paulperry/Library/Jupyter
    /Users/paulperry/anaconda3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/paulperry/Library/Jupyter/runtime
(root) ~>

```
I see nbextension directories both under Library and anaconda3 . How do I resolve this conflict? How do I control the jupyter paths?

**Comment by jcb91** [comment]
@paulperry so, the reason this can happen is that there are multiple places that nbextensions can be installed, as noted in your `jupyter --paths` output (the server looks for them in any `nbextensions` subdirectory of any of the data directories). Essentially there's a per-user directory ` /Users/paulperry/Library/Jupyter`, a per-python (so per-environment) sys-prefix directory `/Users/paulperry/anaconda3/share/jupyter`, and one or more system-wide directories (`/usr/local/share/jupyter`, `/usr/share/jupyter`).

> How do I control the jupyter paths?

If you installed autosametime using the [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) conda package (as opposed to using pip, running `python setup.py`, or `jupyter nbextension ...`), then the installation is performed into the conda sys-prefix directory automatically as part of a post-link script, so you don't get a choice. If you use another install method, then you need to pick where to install yourself, using one or none of the flags `--user`, `--sys-prefix`, or `--system` (see [step two of the install readme](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/a961f47a6da7c0bc6c951ac88916d8c1048f1e23#2-install-javascript-and-css-files) for details). The install docs currently advise the user directory (`--user` flag) by default, which is where your `/Users/paulperry/anaconda3/share/jupyter` copy came from.

> How do I resolve this conflict?

To fix this, you can just remove one of the installations. If you're mostly using anaconda, and run your notebook server from the same environment each time, I would advise using the sys-prefix installation over the user one, particularly since any conda package installation will go there. However, you can keep either, it doesn't matter. To remove the jupyter_contrib_nbextensions install from the user directory, you can use

    jupyter contrib nbextensions uninstall --user

or equivalently to remove the sys-prefix version,

    jupyter contrib nbextensions uninstall --sys-prefix

If you didn't use the jupyter_contrib_nbextensions package, you can uninstall each duplicated nbextension individually, using commands of the form

    jupyter nbextension uninstall --user path/url path/url/entrypoint

e.g.

    jupyter nbextension uninstall --user autosavetime autosavetime/main

Does that make sense?

**Comment by flying-sheep** [comment]
yeah, for me it’s:

```
config:
    /home/$me/.jupyter
    /home/$me/.local/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/$me/.local/share/jupyter
    /home/$me/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /run/user/127365/jupyter
```

note the duplicate `~/.local/share/jupyter`

**Comment by jcb91** [comment]
> note the duplicate `~/.local/share/jupyter`

Yes, strange, and it seems you're missing the sys-prefix location too :thinking:

**Comment by jcb91** [comment]
@flying-sheep it looks suspiciously like your `sys.prefix` is set to `/home/$me/.local/`. Is this perhaps related to #710? Not sure. Could you test

```python
import sys
print(sys.prefix)
```

**Comment by flying-sheep** [comment]
sorry: `sys.prefix == '/usr'`

**Comment by flying-sheep** [comment]
you’re right. that’s how i compiled python! `--prefix=$HOME/.local`

**Comment by jcb91** [comment]
ah! Wait, so `--prefix=$HOME/.local`, but `sys.prefix == '/usr'`? I'm confused :confused:

**Comment by flying-sheep** [comment]
no i deleted that comment as i was wrong (forgot to ssh into the right machine).

`--prefix=$HOME/.local` → `Path(sys.prefix) == Path.home() / '.local'`

**Comment by jcb91** [comment]
ah, ok, I didn't refresh the page, so got both for a while!

So in that case, it might be worth the configurator only checking paths which it hasn't already checked, to cater for duplicates from `jupyter_core.paths`...

**Comment by flying-sheep** [comment]
i bet it’ll work just fine. i just think that stackoverflow code is a bit too clever to easily understand.

**Comment by jcb91** [comment]
:thinking: yes, it's not that clear. I'd go for a set, but the ordering *can* be significant. Perhaps I'll rethink it later...

**Comment by paulperry** [comment]
@jcb91  That worked, thank you.  I removed it from the user directory.

**Comment by jcb91** [comment]
ok, I think this is fixed now, by #35...

**Comment by richdevboston** [comment]
How do I find out specifically WHICH extensions are duplicated, and WHERE the specific duplicates are located? 

I tried the solutions above, but that didn't fix it.   I had to uninstall all NBextensions and reinstall them all and then reboot.  This is a pain, because I lose a lot of time and I have to reinstall the manually installed extensions.
